// AUTO-GENERATED — DO NOT EDIT BY HAND (created 2026-07-15: real per-state economic content to fix scaled-content-abuse pattern on state hub pages)

const stateFacts = {
  "alabama": "Alabama's economy runs on automotive manufacturing (Mercedes-Benz, Hyundai, and Honda all operate plants here), aerospace and defense around Huntsville, and steel production in Birmingham.",
  "alaska": "Alaska's business landscape centers on oil and gas, commercial fishing, and tourism, with many small businesses built around seasonal demand and remote logistics.",
  "arizona": "Arizona's economy has diversified from tourism and construction into semiconductor manufacturing and tech, with Phoenix now a major hub for both.",
  "arkansas": "Arkansas is home to major retail and logistics operations (Walmart's headquarters is in Bentonville), alongside a strong agricultural and food-processing base.",
  "california": "California's business landscape spans technology and venture-backed startups in the Bay Area, entertainment and media in Los Angeles, and one of the largest agricultural economies in the country in the Central Valley.",
  "colorado": "Colorado's economy blends outdoor recreation and tourism with a growing tech and aerospace sector concentrated around Denver and Boulder.",
  "connecticut": "Connecticut has a long-standing base in insurance and financial services, alongside advanced manufacturing tied to aerospace and defense.",
  "delaware": "Delaware is known for its business-friendly corporate law and is home to a large share of the country's incorporated businesses, alongside a strong financial services and chemical manufacturing base.",
  "florida": "Florida's economy is driven by tourism, international trade through its ports, real estate, and a fast-growing base of small businesses in hospitality and service industries.",
  "georgia": "Georgia's economy centers on logistics and distribution (Atlanta's airport is one of the busiest in the world), film and media production, and a growing fintech sector.",
  "hawaii": "Hawaii's business landscape is shaped heavily by tourism and hospitality, with small businesses often navigating high operating costs and seasonal demand.",
  "idaho": "Idaho's economy combines a strong agricultural base — the state leads the nation in potato production — with a growing technology sector centered in Boise.",
  "illinois": "Illinois' economy is anchored by Chicago's role as a national hub for finance, logistics, and manufacturing, alongside a substantial agricultural base downstate.",
  "indiana": "Indiana has a strong manufacturing base in automotive parts, pharmaceuticals, and logistics, with Indianapolis serving as a major distribution hub.",
  "iowa": "Iowa's economy is built around agriculture and food processing, along with a growing renewable energy and insurance sector centered in Des Moines.",
  "kansas": "Kansas combines a strong agricultural economy with aerospace manufacturing centered in Wichita, home to several major aircraft manufacturers.",
  "kentucky": "Kentucky's economy includes automotive manufacturing, bourbon production, and logistics, with Louisville serving as a major air cargo hub.",
  "louisiana": "Louisiana's economy is shaped by the energy sector, port and shipping activity along the Mississippi River, and a tourism industry centered on New Orleans.",
  "maine": "Maine's economy relies on tourism, fishing and seafood processing, and a growing base of small manufacturers and specialty food producers.",
  "maryland": "Maryland's economy is shaped by federal government contracting, biotechnology, and the Port of Baltimore, with a strong professional services sector near Washington, D.C.",
  "massachusetts": "Massachusetts is a national hub for biotechnology, higher education, and technology, with a dense concentration of startups and research institutions around Boston.",
  "michigan": "Michigan's economy remains deeply tied to automotive manufacturing, alongside growing advanced manufacturing and mobility-tech sectors around Detroit.",
  "minnesota": "Minnesota's economy includes major healthcare and medical device companies, food processing, and a strong base of Fortune 500 corporate headquarters around Minneapolis-St. Paul.",
  "mississippi": "Mississippi's economy includes shipbuilding and manufacturing along the Gulf Coast, agriculture, and a growing furniture manufacturing industry.",
  "missouri": "Missouri's economy spans agriculture, aerospace manufacturing in St. Louis, and logistics, benefiting from its central location and major transportation corridors.",
  "montana": "Montana's economy relies on agriculture, tourism tied to its national parks, and a growing base of small manufacturers and outdoor recreation businesses.",
  "nebraska": "Nebraska's economy is built on agriculture and food processing, along with a notable concentration of insurance and financial services headquartered in Omaha.",
  "nevada": "Nevada's economy centers on tourism, hospitality, and entertainment in Las Vegas, alongside a growing logistics and manufacturing base benefiting from the state's tax structure.",
  "new-hampshire": "New Hampshire's economy includes advanced manufacturing, technology, and a strong small business base benefiting from the state's lack of sales and income tax.",
  "new-jersey": "New Jersey's economy is shaped by pharmaceuticals, logistics tied to its ports, and proximity to both New York City and Philadelphia business markets.",
  "new-mexico": "New Mexico's economy includes national laboratory and defense-related research, energy production, and a growing film production industry.",
  "new-york": "New York's economy spans global finance and professional services in Manhattan, along with manufacturing, agriculture, and tourism throughout the rest of the state.",
  "north-carolina": "North Carolina's economy includes banking and finance centered in Charlotte, biotechnology and research in the Raleigh-Durham area, and traditional manufacturing.",
  "north-dakota": "North Dakota's economy is shaped by energy production tied to the Bakken oil formation, along with a substantial agricultural base.",
  "ohio": "Ohio's economy includes advanced manufacturing, healthcare, and logistics, with several major metro areas serving as regional distribution hubs.",
  "oklahoma": "Oklahoma's economy is shaped by energy production, aerospace manufacturing tied to Tinker Air Force Base, and agriculture.",
  "oregon": "Oregon's economy includes technology manufacturing (particularly semiconductors), outdoor apparel and footwear companies, and a growing craft food and beverage industry.",
  "pennsylvania": "Pennsylvania's economy spans healthcare and education around Philadelphia, energy production, and manufacturing, with Pittsburgh's economy having shifted toward technology and robotics.",
  "rhode-island": "Rhode Island's economy includes healthcare, education, marine trades tied to its coastline, and a growing base of small manufacturers and design businesses.",
  "south-carolina": "South Carolina's economy includes automotive and aerospace manufacturing (BMW and Boeing both operate major plants here), along with tourism along its coast.",
  "south-dakota": "South Dakota's economy benefits from a favorable tax structure that has attracted financial services and credit card companies, alongside a strong agricultural base.",
  "tennessee": "Tennessee's economy spans healthcare management companies headquartered in Nashville, automotive manufacturing, and a growing logistics sector tied to FedEx's hub in Memphis.",
  "texas": "Texas has one of the largest and most diverse state economies in the country, spanning energy, technology, healthcare, and a rapidly growing base of small businesses across its major metro areas.",
  "utah": "Utah's economy includes a fast-growing technology sector along the Silicon Slopes corridor, along with mining, agriculture, and outdoor recreation industries.",
  "vermont": "Vermont's economy relies on tourism, specialty food and beverage production, and a strong base of small manufacturers and artisan businesses.",
  "virginia": "Virginia's economy is shaped by federal government contracting and technology near Washington, D.C., along with a significant data center industry and agricultural base.",
  "washington": "Washington's economy is anchored by technology and aerospace giants headquartered in the Seattle area, along with a substantial agricultural and shipping industry.",
  "west-virginia": "West Virginia's economy includes energy production, chemical manufacturing, and a growing tourism industry tied to its outdoor recreation opportunities.",
  "wisconsin": "Wisconsin's economy includes manufacturing, agriculture (particularly dairy), and a growing healthcare and insurance sector centered in Milwaukee.",
  "wyoming": "Wyoming's economy is shaped by energy and mineral extraction, tourism tied to its national parks, and a favorable tax environment for small businesses."
};

export default stateFacts;
